url_simplify/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'url_simplify'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:url_id>/delete/', views.delete_url, name='delete_url'),
    path('urls/', views.UrlsView.as_view(), name='urls'),
    path('shortify/', views.add_url, name='add_url'),
    path(settings.SHORT_PREFIX + '<str:short_id>/',
         views.short_redirect, name='short_redirect')
]

url_simplify/models.py
from django.db import models
from django.conf import settings
from shortuuid import ShortUUID


class Url(models.Model):
    full_url = models.CharField(max_length=2083)
    short_id = models.CharField(max_length=200)
    redirects = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s, %d" % (self.full_url, self.redirects)

    @staticmethod
    def gen_short_id():
        """
        Helper which randomly generates base62 id
        """
        return ShortUUID().random(length=settings.SHORT_ID_LEN)

url_simplify/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect,  Http404
from django.urls import reverse
from django.views import generic
from .models import Url


URLS_PAGINATION = 10
MOST_POPULAR_COUNT = 20


class IndexView(generic.ListView):
    template_name = 'url_simplify/index.html'
    context_object_name = 'popular_url_list'

    def get_queryset(self):
        """
        Return the most popular `MOST_POPULAR_COUNT` objects,
        based on redirects and created_at
        """
        return get_most_popular()[:MOST_POPULAR_COUNT]


class DetailView(generic.DetailView):
    model = Url
    template_name = 'url_simplify/detail.html'


class UrlsView(generic.ListView):
    template_name = 'url_simplify/urls_list.html'
    context_object_name = 'url_list'
    paginate_by = URLS_PAGINATION

    def get_queryset(self):
        """
        Pass most popular urls based on `get_most_popular()`
        """
        return get_most_popular()


def short_redirect(request, short_id):
    """
    Handles redirects for shortened urls, every time user request this,
    force redirect and increment redirect count for particular `Url` object
    """
    url = get_object_or_404(Url, short_id=short_id)
    url.redirects += 1
    url.save()
    redirect_url = url.full_url
    if not redirect_url.startswith('http://'):
        if not redirect_url.startswith('https://'):
            redirect_url = 'http://' + redirect_url
    return HttpResponseRedirect(redirect_url)


def add_url(request):
    """
    Url shortener form action
    """
    input_url = request.POST.get('input_url', '')
    # in case 'input_url' is not provided by POST request
    if not input_url:
        return HttpResponseRedirect(reverse('url_simplify:index'))
    short_id = Url.gen_short_id()
    # check if already exists, if so, try one to generate one more time
    tmp = Url.objects.filter(short_id=short_id)
    if tmp:
        return Http404("Something went wrong. Please, try one more time")
    url = Url(full_url=input_url, short_id=short_id)
    url.save()
    return HttpResponseRedirect(reverse('url_simplify:detail',
                                        args=(url.id,)))


def delete_url(request, url_id):
    """
    Url remove handler
    """
    p = Url.objects.get(pk=url_id)
    p.delete()
    return HttpResponseRedirect(reverse('url_simplify:urls'))


def get_most_popular():
    """
    Helper which retrieves most popular urls based on `redirects`(desc) and
    `created_at`(desc)
    """
    return Url.objects.order_by('-redirects', '-created_at')

url_simplify/templates/url_simplify/detail.html
<h1>
  <a href="{% url 'url_simplify:index' %}">URL simplifier</a>
</h1>
<h2>
  <a href="{% url 'url_simplify:urls' %}">All urls</a>
</h2>

<style type="text/css">
td
{
    padding:0 50px 0 50px;
}
</style>

<table id="urls">
    <tr>
      <th>created_at</th>
      <th>full_url</th>
      <th>redirects</th>
      <th>short_id</th>
      <th>short_url</th>
    </tr>
        <tr>
            <td>{{ url.created_at|date:'Y-m-d H:i' }}</td>
            <td>{{ url.full_url }}</td>
            <td>{{ url.redirects }}</td>
            <td>{{ url.short_id }}</td>
            <td>
              <a href="{% url 'url_simplify:short_redirect' url.short_id %}">{% url 'url_simplify:short_redirect' url.short_id %}</a>
            </td>
        </tr>
</table>

url_simplify/templates/url_simplify/index.html
<h1>URL simplifier</h1>
<h2>
  <a href="{% url 'url_simplify:urls' %}">All urls</a>
</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'url_simplify:add_url' %}" method="post">
{% csrf_token %}
<input name="input_url" placeholder="Your original URL here" required/>
<input type="submit" value="Shorten URL" />
</form>

{% if popular_url_list %}
    <h3>Most popular urls</h3>
    <ol>
    {% for url in popular_url_list %}
        <li><a href="{% url 'url_simplify:detail' url.id %}">{{ url.full_url }}, {{ url.redirects }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No simplified urls are available.</p>
{% endif %}

url_simplify/templates/url_simplify/urls_list.html
<h1>
  <a href="{% url 'url_simplify:index' %}">URL simplifier</a>
</h1>
<h2>
  All urls
</h2>

<style type="text/css">
td
{
    padding:0 50px 0 50px;
}
</style>

{% if url_list %}
    <table id="urls">
        <tr>
          <th>created_at</th>
          <th>full_url</th>
          <th>redirects</th>
          <th>short_id</th>
          <th>short_url</th>
          <th>delete</th>
        </tr>
        {% for url in url_list %}
            <tr>
                <td>{{ url.created_at|date:'Y-m-d H:i' }}</td>
                <td>{{ url.full_url }}</td>
                <td>{{ url.redirects }}</td>
                <td>{{ url.short_id }}</td>
                <td>
                  <a href="{% url 'url_simplify:short_redirect' url.short_id %}">{% url 'url_simplify:short_redirect' url.short_id %}</a>
                </td>
                <td>
                  <a type="button" href="{% url 'url_simplify:delete_url' url.id %}">remove</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        {% else %}
          <span class="disabled">&laquo;</span>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <span class="active">{{ i }} <span class="sr-only">(current)</span></span>
          {% else %}
            <a href="?page={{ i }}">{{ i }}</a>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        {% else %}
          <span class="disabled">&raquo;</span>
        {% endif %}
      </span>
      </div>
    {% endif %}
{% else %}
    <h3>Urls</h3>
    <p>No urls found!!! :(</p>
{% endif %}